const shows = [
{
    id: "semantic-error",
    title: "Semantic Error",
    poster: "posters/semantic-error.jpg",
    country: "Korea",
    year: 2022,
    episodes: 8,
    rating: 12,
    chemistry: 5,
    progression: 5,
    emotionalImpact: 4,
    acting: 5,
    rewatchability: 5,
    mood: "Comfort",
    tropes: ["Enemies to Lovers", "College", "Slow Burn"],
    miniReview: "One of my ultimate comfort shows. The progression between Sangwoo and Jaeyoung is what makes it so rewatchable.",
    favoriteScene: "When Sangwoo starts changing little habits, like not wearing his hat.",
    status: "Completed"
    },
    {
    id: "our-dining-table",
    title: "Our Dining Table",
    poster: "posters/our-dining-table.jpg",
    country: "Japan",
    year: 2023,
        episodes: 10,
        rating: 10,
        chemistry: 5,
        progression: 5,
        emotionalImpact: 4,
        acting: 5,
        rewatchability: 5,
        mood: "Comfort",
        tropes: ["Family", "Food", "Slice of Life"],
        miniReview: "A heartwarming show about the importance of family and sharing meals together.",
        favoriteScene: "The scene where the family gathers for dinner and shares their day.",
        status: "Completed"
    },
    {
    id: "the-eighth-sense",
    title: "The Eighth Sense",
    poster: "posters/the-eighth-sense.jpg",
    country: "Korea",
    year: 2023,
        episodes: 10,
        rating: 11,
        chemistry: 5,
        progression: 5,
        emotionalImpact: 4,
        acting: 5,
        rewatchability: 5,
        mood: "Emotional",
        tropes: ["Family", "Food", "Slice of Life"],
        miniReview: "A heartwarming show about the importance of family and sharing meals together.",
        favoriteScene: "The scene where the family gathers for dinner and shares their day.",
        status: "Completed"
    }

];